"""membuat table user

Revision ID: a19df0fc240d
Revises: 
Create Date: 2026-02-18 13:58:41.841564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a19df0fc240d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('best_selling_games')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('best_selling_games',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('game_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('reviews_like_rate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('all_reviews_number', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('release_date', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('developer', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_defined_tags', mysql.TEXT(), nullable=True),
    sa.Column('supported_os', mysql.TEXT(), nullable=True),
    sa.Column('supported_languages', mysql.TEXT(), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('other_features', mysql.TEXT(), nullable=True),
    sa.Column('age_restriction', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('rating', mysql.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('difficulty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('length', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('estimated_downloads', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
